#include "utils/Setup.hpp"
#include "instruction/Instructions.hpp"

CEREAL_REGISTER_TYPE(Instruction)
CEREAL_REGISTER_TYPE(Assignment)
CEREAL_REGISTER_TYPE(Block)
CEREAL_REGISTER_TYPE(Break)
CEREAL_REGISTER_TYPE(Continue)
CEREAL_REGISTER_TYPE(Call)
CEREAL_REGISTER_TYPE(CreateFunction)

CEREAL_REGISTER_POLYMORPHIC_RELATION(Instruction, Assignment)
CEREAL_REGISTER_POLYMORPHIC_RELATION(Instruction, Block)
CEREAL_REGISTER_POLYMORPHIC_RELATION(Instruction, Break)
CEREAL_REGISTER_POLYMORPHIC_RELATION(Instruction, Continue)
CEREAL_REGISTER_POLYMORPHIC_RELATION(Instruction, Call)
CEREAL_REGISTER_POLYMORPHIC_RELATION(Instruction, CreateFunction)