#pragma once
#include <iostream>
#include <tuple>
#include <vector>
#include <string>
#include <regex>
#include <cctype>
#include <unordered_map>
#include <cstdlib>
#include <sstream>
#include <iomanip>
#include <algorithm>
#include <fstream>
#include <memory>
#include <cmath>
#include <chrono>
#include <thread>
#include <cstring>
#include <random>
#include <functional>
#include <filesystem>
#include <exception>
#include <stdexcept>
#include <future>

#include "cereal/cereal.hpp"
#include "cereal/archives/binary.hpp"
#include "cereal/archives/portable_binary.hpp"

#include "cereal/types/memory.hpp"
#include "cereal/types/string.hpp"
#include "cereal/types/tuple.hpp"
#include "cereal/types/vector.hpp"
#include "cereal/types/polymorphic.hpp"
