#pragma once
#include <iostream>
#include <tuple>
#include <vector>
#include <string>
#include <regex>
#include <cctype>
#include <unordered_map>
#include <cstdlib>
#include <sstream>
#include <iomanip>
#include <algorithm>
#include <fstream>
#include <memory>
#include <cmath>
#include <chrono>
#include <thread>
#include <cstring>
#include <random>
#include <functional>
#include <filesystem>
#include <exception>
#include <stdexcept>
#include <future>
